DB_USER = "postgres_user"
DB_PASSWORD = "RiddhiSiddhi246!"
DB_HOST = "inventory-db-instance.czmwusiwewpk.us-east-2.rds.amazonaws.com"
LAMBDA_API_URL = "https://jwfv3whasofhjtxsdxxtqss4py0uavoz.lambda-url.us-east-2.on.aws/"
OPENAI_API_KEY = "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"
PINECONE_API_KEY = "pcsk_6pBXB2_7EnyeZVgWXoJFaqPLL1U3pGcGNWi8scUBo83MoQc1NaFkWPxQ1ULMdNJ6QmuNPE"
DB_NAME = "inventory_platform"
DB_PORT = "5432"
